version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.25
    - 14.14.26
    - 14.14.28
    - 14.14.30
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: next-pwa
    versions:
    - 5.0.4
    - 5.0.5
    - 5.0.6
    - 5.1.4
    - 5.2.1
    - 5.2.14
    - 5.2.3
    - 5.2.5
    - 5.2.9
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.14.1
    - 4.14.2
    - 4.15.0
    - 4.15.1
    - 4.15.2
    - 4.16.1
    - 4.17.0
    - 4.18.0
    - 4.19.0
    - 4.20.0
    - 4.21.0
  - dependency-name: styled-components
    versions:
    - 5.2.1
    - 5.2.2
  - dependency-name: husky
    versions:
    - 4.3.8
    - 5.0.9
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: "@testing-library/react"
    versions:
    - 11.2.3
    - 11.2.5
  - dependency-name: node-notifier
    versions:
    - 8.0.1
